image: edbizarro/gitlab-ci-pipeline-php:8.2

pipelines:
  branches:
    main:
      - step:
          name: Build & Deploy to Combell
          caches:
            - composer
            - node
          script:
            # Print PHP extensions
            - php -m

            # Install Composer dependencies
            - composer install --no-dev --optimize-autoloader

            # Build frontend assets
            - npm install
            - npm run build

            # SSH config
            - mkdir -p ~/.ssh
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh-keyscan ssh101.webhosting.be >> ~/.ssh/known_hosts

            # Deploy backend (PHP/DB) via Deployer
            - php vendor/bin/dep deploy staging

            # Upload frontend (dist) assets
            - rsync -avz ./web/dist/ imprentabe@ssh101.webhosting.be:/data/sites/web/imprenta/subsites/staging.imprenta.be/web/dist/
