cleanupProbability: 1000
enable404RedirectLog: false
globallyExcludedUrlPatterns: null
matchDefinition: urlWithoutQueryStrings
queryStringStrategy: removeQueryStrings
structureUid: f5eae54d-29d3-4899-b2fd-1fcc9dd474e1
total404Redirects: 250
trackRemoteIp: false
