color: null
fieldLayouts:
  b05985c5-3035-47a7-835b-b5b6df05a261:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-17T12:44:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19c9a2b7-292b-4dc8-a2af-3a1b62a08c52
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-17T12:46:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: caf0a72c-d4ed-424e-afbc-8c3b2e7ee93a # Columns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52624c51-e492-4b97-994e-f28aa3e677ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87ccd5dd-416f-42a7-a709-9447f914db3d
        userCondition: null
handle: columns
hasTitleField: true
icon: null
name: Columns
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
