color: null
fieldLayouts:
  83df7137-8ff5-4bee-8c25-b7b7787f1e63:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-08T21:40:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b6e414b6-333c-42a0-a48c-0e14dcd6cb7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T21:45:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 66075bdc-827d-4275-a8c1-9c350786e7cc # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acbc21ab-3a73-4928-b0c2-b88eeb6f2596
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T21:45:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: df402d3e-ddfa-4994-a215-f5ad8cce0e7d # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ad5a73-3091-41b6-a394-c236e4148699
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T21:45:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d64ae2db-e6e5-4c44-954c-57bd79fc6321 # CTA Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3b5f5ac-bdf4-425f-963a-d14a65d2cf44
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T21:09:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8ad5f1a-d8a7-4bbb-89a4-7c294aaaa971 # Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5d0459d-4294-4bc3-a140-3226cf3cf4ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f61383f7-5f0b-48f5-8705-12b8333fb5d5
        userCondition: null
handle: ctaText
hasTitleField: true
icon: align-justify
name: 'Text + CTA'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
