color: null
fieldLayouts:
  27dcb1f7-706f-4a3c-8af1-a48d68f5bbfe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-27T22:01:54+00:00'
            elementCondition: null
            heading: Homepagina
            type: craft\fieldlayoutelements\Heading
            uid: 86629f2d-7004-4d05-895c-eae8f2213585
            userCondition: null
          -
            dateAdded: '2025-02-27T22:17:31+00:00'
            elementCondition: null
            fieldUid: f34aad52-4756-44e0-b970-78813ee16a13 # Slider
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b534045e-a9c9-4aed-aa6b-e0102486e2bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-01T23:27:09+00:00'
            elementCondition: null
            fieldUid: 94655389-9aaa-41cf-a493-c34178a44ec2 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77a1e73a-63a3-41ee-9e2b-15fece1741b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-16T21:52:38+00:00'
            elementCondition: null
            fieldUid: b0af7fa0-30d5-49ab-87d6-2f91da10bbc6 # Project Slider
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015c069a-4ab6-4f0f-8ec3-539605078cc5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-17T21:38:00+00:00'
            elementCondition: null
            fieldUid: 1a5c74d4-7b0e-4d0b-9d95-0f6831237fab # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2b90156-e069-4a49-85d2-735540251d1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1629b566-11cb-4712-b81b-7a1900a55dcf
        userCondition: null
handle: homepage
hasTitleField: false
icon: page
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
