color: null
fieldLayouts:
  33305925-b55c-4171-b85a-89042d06d691:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-16T21:49:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 37af9497-d99e-4419-86b7-9a571d7a9e91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-16T21:53:50+00:00'
            elementCondition: null
            fieldUid: b0af7fa0-30d5-49ab-87d6-2f91da10bbc6 # Project Slider
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f185d6d-8a34-461d-a18c-b9e9062bf8c3
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 0445ffa1-47c7-4931-8e80-01c9707373ae
        userCondition: null
handle: projectSlider
hasTitleField: true
icon: angle-right
name: 'Project Slider'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
