color: null
fieldLayouts:
  f65e5c4f-4d8d-45a8-9f55-402557577819:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-09T21:18:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15fcdc43-aea5-4bff-bb58-d7f667ef471a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-09T21:20:25+00:00'
            elementCondition: null
            fieldUid: df402d3e-ddfa-4994-a215-f5ad8cce0e7d # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd74d702-6326-4e15-9395-43c8b9095f86
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ffdac17-88af-4d67-8bcc-e10533d80bdf
        userCondition: null
handle: sidebar
hasTitleField: true
icon: align-left
name: Sidebar
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
