color: null
fieldLayouts:
  210591b4-15b7-4165-90fe-00dfe7112ede:
    cardView:
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-20T15:38:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8868172e-48e1-4649-a131-2ece1cc6ce95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-20T15:40:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: df402d3e-ddfa-4994-a215-f5ad8cce0e7d # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a45dc415-c731-4fc9-b74b-48501425ff1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-21T19:26:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f34aad52-4756-44e0-b970-78813ee16a13 # Slider
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a868a921-bd9a-42e1-a739-785d8fc79fb5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8048d2f2-6a4f-41b8-8718-1a2cb434352b
        userCondition: null
handle: subservice
hasTitleField: true
icon: null
name: Subservice
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
