color: null
fieldLayouts:
  c6963291-3a8c-40e1-b438-bb41699634a6:
    cardView:
      - uri
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-07T21:02:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e4fb77cf-570f-4be4-a413-11244992416d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-07T21:13:16+00:00'
            elementCondition: null
            fieldUid: df402d3e-ddfa-4994-a215-f5ad8cce0e7d # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fddaea7-c838-4587-9346-5ee5c8de7db1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15788dad-c5c8-4a70-926c-0f3436055640
        userCondition: null
handle: vacancyListing
hasTitleField: true
icon: address-book
name: 'Vacancy Listing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
