baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: nl-BE
name: 'Betonbouw en grondwerken - Lavens'
primary: true
siteGroup: 38a8e666-e3bc-45ce-ba85-0dda8e172c54 # Betonbouw en grondwerken - Lavens
sortOrder: 1
