tabs:
  -
    elementCondition: null
    elements:
      -
        attribute: oldUrl
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        autofocus: false
        class: null
        dateAdded: '2025-03-31T21:50:50+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        mandatory: true
        max: null
        maxlength: 255
        min: null
        name: null
        orientation: null
        placeholder: old/page/location
        providesThumbs: false
        readonly: false
        requirable: false
        required: true
        size: null
        step: null
        tip: null
        title: null
        translatable: false
        type: BarrelStrength\Sprout\redirects\components\elements\fieldlayoutelements\OldUrlField
        uid: 68cbba86-04c5-454b-bc7e-2cac4f1df26f
        userCondition: null
        warning: null
        width: 100
      -
        attribute: newUrl
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        autofocus: true
        class: null
        dateAdded: '2025-03-31T21:50:50+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        mandatory: true
        max: null
        maxlength: 255
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        required: false
        size: null
        step: null
        tip: null
        title: null
        translatable: false
        type: BarrelStrength\Sprout\redirects\components\elements\fieldlayoutelements\NewUrlField
        uid: 07e8b96d-b4ed-4c6f-8f13-d2fbde7b160b
        userCondition: null
        warning: null
        width: 100
      -
        attribute: statusCode
        dateAdded: '2025-03-31T21:50:50+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        mandatory: true
        orientation: null
        providesThumbs: false
        requirable: false
        required: true
        tip: null
        translatable: false
        type: BarrelStrength\Sprout\redirects\components\elements\fieldlayoutelements\StatusCodeField
        uid: 8dd39c53-02af-4e75-b848-6217240cae6e
        userCondition: null
        warning: null
        width: 100
      -
        attribute: matchStrategy
        dateAdded: '2025-03-31T21:50:50+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        mandatory: true
        orientation: null
        providesThumbs: false
        requirable: false
        required: true
        tip: null
        translatable: false
        type: BarrelStrength\Sprout\redirects\components\elements\fieldlayoutelements\MatchStrategyField
        uid: b27b1205-e9ef-4a93-89cf-83a0c579f63e
        userCondition: null
        warning: null
        width: 100
    name: Inhoud
    uid: 7018cec2-f09d-41d3-8ac8-e0fca75bd860
    userCondition: null
