columnSuffix: null
handle: ctaButton
instructions: null
name: 'CTA Button'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - entry
    - url
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
