columnSuffix: null
handle: footerTelefoon
instructions: 'Schijf hier het telefoonnummer voor in de footer'
name: 'Footer Telefoon'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
