columnSuffix: null
handle: footerAdres
instructions: 'Schijf hier het adres voor in de footer: straat, nummer - postcode, gemeente - land'
name: 'Footer Adres'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: null
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
