columnSuffix: null
handle: heading
instructions: null
name: Heading
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Heading '
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
