columnSuffix: null
handle: intro
instructions: null
name: Intro
searchable: false
settings:
  createButtonLabel: Intro
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - db65710f-c642-4673-8649-177516332d5b # Intro
  includeTableView: false
  maxEntries: 5
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
