columnSuffix: null
handle: intro
instructions: 'Voeg hier de introtekst in voor deze pagina.'
name: Intro
searchable: false
settings:
  createButtonLabel: Intro
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - db65710f-c642-4673-8649-177516332d5b # Intro
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
