columnSuffix: null
handle: navLink
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
