columnSuffix: null
handle: position
instructions: 'Hoe moet het de content worden weergegeven, tekst links, tekst rechts, gecentreerd?'
name: Position
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Gecentreerd
        -
          - value
          - centered
        -
          - icon
          - align-justify
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Tekst links'
        -
          - value
          - textLeft
        -
          - icon
          - align-justify
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Tekst rechts'
        -
          - value
          - texRight
        -
          - icon
          - align-right
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
