columnSuffix: null
handle: showInMenu
instructions: null
name: 'Show in Menu'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
