fieldLayouts:
  32a56178-3545-4727-a66c-6f31777ce554:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-17T21:15:10+00:00'
            elementCondition: null
            fieldUid: d659ffc8-826e-4334-a065-37a268b7cb67 # Header Sitelogo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 206026a8-9b6e-4f7a-9688-b52d90d88b5f
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 21e0aca3-0d26-4f57-830c-2ef82a545690
        userCondition: null
handle: header
name: Header
sortOrder: 3
