defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cc0cda22-0084-4cc6-b0bb-4ad82ddc44a1 # Blog Post
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d3e33d75-0505-4fc0-bc07-acefbb69a249: # Imprenta
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
