defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 796b21ff-3ef3-4fd8-b7b3-29a35c5e48e9 # Homepage
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d3e33d75-0505-4fc0-bc07-acefbb69a249: # Imprenta
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: __home__
type: single
